options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'node:20-slim'
    entrypoint: 'npm'
    args: ['install']
    dir: 'blog-platform-frontend'

  - name: 'node:20-slim'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'blog-platform-frontend'

  - name: 'node:20-slim'
    entrypoint: 'npx'
    args: 
      - firebase
      - deploy
      - '--project=${PROJECT_ID}'
      - '--only=hosting'
    dir: 'blog-platform-frontend' 

timeout: 600s