options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'blog-platform-frontend'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'blog-platform-frontend'

  # Bước 2: Deploy lên Firebase Hosting
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: 
      - gcloud
      - firebase
      - deploy
      - '--project=${PROJECT_ID}'
      - '--only=hosting'
    entrypoint: bash
timeout: 600s